### ISSUE TITLE
save slot status not saving properly

### ISSUE THREAD

**Issue by cxhernandez** [FoldingAtHome/fah-client-pub#1170] opened 2016-09-12 20:18 UTC
muziqaz writes:

>@jcoffland I see that new client still does not save slot status properly. I just paused the GPU slots, waited till they are paused. And rebooted PC. When Win fully loaded, the slots were not in paused mode anymore. They just started as normal. This used to be major pain for me with .4.4 version since I would finish the slot not wanting for it to get anymore WUs, I would manually pause it after its finished. Switch off the PC, and next day when I switch on PC to do something with it, folding slot would just start up ignoring my manual pause and pick up a WU. So I would have to either dump the WU or pause it and keep it paused for whatever period I was doing something with PC unrelated to folding.

**Comment by jcoffland** [comment] 2016-09-12 23:36
The client does save pause status.  I believe this is really a duplicate of #783.

**Closed by jcoffland** 2016-09-12 23:36 UTC

**Comment by bb30994** [comment] 2016-09-13 18:49
He'd like the finish function to create a pause that survives after a reboot, but he specifically says he's doing a manual pause and it's not being preserved.

In my experience, a manual pause is, in fact, preserved, so I don't understand his report.

In any case, there's the case of rebooting BEFORE the WU is finished, which is what #783 is asking for, and the status says something like "Paused - Finished" That apparently is not the same as "paused" status which is what you get when you do a manual pause.  (at least the messages are different).
